# hurasiaweb/Dockerfile
FROM node

WORKDIR /workspace

COPY package*.json ./

# 2. 의존성 설치
RUN npm install

# 3. 나머지 소스 복사
COPY . .

# Set the port environment variable to 8000
ENV PORT=8000

# Expose port 8000
EXPOSE 8000

CMD ["npm", "start"]